import { Track } from 'react-native-track-player';

export const MEDIA_QUERY_BREAKPOINT_PX = 768;

export const sampleSongData: Track[] = [
  {
    id: 0,
    url: 'assets/songs/blizzard.mp3',
    title: 'Blizzard',
    artist: 'Kiki, Mimi, & Mini',
    album: 'if(onlySilent)',
    genre: 'Classical',
    date: '2022-06-20T07:00:00+00:00',
    artwork: 'assets/artwork/blizzard.avif',
    duration: 3.02,
  },
  {
    id: 1,
    url: 'assets/songs/nova.mp3',
    title: 'Nova',
    artist: 'Vivi Freezy',
    album: 'Celestial Wonders',
    genre: 'Classical',
    date: '2014-05-20T07:00:00+00:00',
    artwork: 'assets/artwork/stars.avif',
    duration: 3.53,
  },
  {
    id: 2,
    url: 'assets/songs/shaman.mp3',
    title: 'Shaman',
    artist: 'Jungmorpheus',
    album: 'O1.',
    genre: 'New Age',
    date: '2020-06-20T07:00:00+00:00',
    artwork: 'assets/artwork/shaman.avif',
    duration: 2.18,
  },
  {
    id: 3,
    url: 'assets/songs/perfect-beauty.mp3',
    title: 'Perfect Beauty',
    artist: 'Jungmorpheus',
    album: 'O1.',
    genre: 'New Age',
    date: '2020-06-20T07:00:00+00:00',
    artwork: 'assets/artwork/shaman.avif',
    duration: 7.20,
  },
  {
    id: 4,
    url: 'assets/songs/summer-walk.mp3',
    title: 'Fly You To The Sky × Free Fall',
    artist: 'Jungmorpheus',
    album: 'O1.',
    genre: 'New Age',
    date: '2020-06-20T07:00:00+00:00',
    artwork: 'assets/artwork/shaman.avif',
    duration: 3.17,
  },
];
